services:
  - type: web
    name: group-project-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0

